import { Course, Module, Lesson, User, UserProgress } from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'trainee@forge.com',
    name: 'Nguyễn Văn Minh',
    role: 'trainee',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-24'),
  },
  {
    id: '2',
    email: 'admin@forge.com',
    name: 'Trần Thị Hoa',
    role: 'course_admin',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-02-24'),
  },
  {
    id: '3',
    email: 'platform@forge.com',
    name: 'Lê Quốc Đạt',
    role: 'platform_admin',
    createdAt: new Date('2023-12-01'),
    updatedAt: new Date('2024-02-24'),
  },
];

export const mockCourses: Course[] = [
  {
    id: '1',
    title: 'Kiến Thức Cơ Bản Về Bất Động Sản',
    description: 'Nắm vững kiến thức nền tảng về thị trường bất động sản Việt Nam, các loại hình BĐS phổ biến và thuật ngữ chuyên ngành cần thiết cho người môi giới.',
    category: 'Bất Động Sản',
    creatorId: '2',
    status: 'published',
    imageUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&h=300&fit=crop',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    id: '2',
    title: 'Kỹ Năng Tư Vấn Khách Hàng',
    description: 'Học cách khai thác nhu cầu khách hàng, tư vấn sản phẩm phù hợp và xây dựng mối quan hệ bền vững với khách hàng trong lĩnh vực bất động sản.',
    category: 'Kỹ Năng Bán Hàng',
    creatorId: '2',
    status: 'published',
    imageUrl: 'https://images.unsplash.com/photo-1556761175-4b46a572b786?w=400&h=300&fit=crop',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: '3',
    title: 'Kỹ Năng Chốt Sale Bất Động Sản',
    description: 'Thành thạo kỹ năng xử lý phản đối, đàm phán giá và chốt giao dịch thành công trong các tình huống bán bất động sản thực tế.',
    category: 'Kỹ Năng Bán Hàng',
    creatorId: '2',
    status: 'published',
    imageUrl: 'https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?w=400&h=300&fit=crop',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: '4',
    title: 'Pháp Lý Bất Động Sản',
    description: 'Tìm hiểu quy trình pháp lý mua bán, hợp đồng công chứng, và các quy định pháp luật liên quan đến giao dịch bất động sản tại Việt Nam.',
    category: 'Pháp Lý',
    creatorId: '2',
    status: 'published',
    imageUrl: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=400&h=300&fit=crop',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-22'),
  },
  {
    id: '5',
    title: 'Mô Phỏng Bán Hàng AI - Căn Hộ Chung Cư',
    description: 'Luyện tập kỹ năng tư vấn bán căn hộ chung cư cho khách hàng AI. Trải nghiệm tình huống bán hàng thực tế với dự án The Emerald 68, Bình Dương.',
    category: 'Mô Phỏng AI',
    creatorId: '2',
    status: 'published',
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=400&h=300&fit=crop',
    createdAt: new Date('2024-02-24'),
    updatedAt: new Date('2024-02-24'),
  },
  {
    id: '6',
    title: 'Mô Phỏng Bán Hàng AI - Nhà Phố',
    description: 'Luyện tập kỹ năng tư vấn bán nhà phố cho khách hàng AI. Trải nghiệm tình huống bán hàng thực tế với dự án Verosa Park, Quận 9, TP.HCM.',
    category: 'Mô Phỏng AI',
    creatorId: '2',
    status: 'published',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: '7',
    title: 'Mô Phỏng Bán Hàng AI - Biệt Thự',
    description: 'Luyện tập kỹ năng tư vấn bán biệt thự cao cấp cho khách hàng AI. Trải nghiệm tình huống bán hàng thực tế với dự án Vinhomes Central Park.',
    category: 'Mô Phỏng AI',
    creatorId: '3',
    status: 'published',
    imageUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=400&h=300&fit=crop',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-12'),
  },
  {
    id: '8',
    title: 'Mô Phỏng Bán Hàng AI - Đất Nền',
    description: 'Luyện tập kỹ năng tư vấn bán đất nền cho khách hàng AI. Trải nghiệm tình huống bán hàng thực tế với đất nền khu vực Long Thành, Đồng Nai.',
    category: 'Mô Phỏng AI',
    creatorId: '2',
    status: 'published',
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&h=300&fit=crop',
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-03-18'),
  },
  {
    id: '9',
    title: 'Mô Phỏng Bán Hàng AI - Shophouse',
    description: 'Luyện tập kỹ năng tư vấn bán shophouse cho khách hàng AI. Trải nghiệm tình huống bán hàng thực tế với dự án Vinhomes Grand Park, TP. Thủ Đức.',
    category: 'Mô Phỏng AI',
    creatorId: '2',
    status: 'published',
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=300&fit=crop',
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-03-20'),
  },
];

export const mockModules: Record<string, Module[]> = {
  '1': [
    {
      id: 'm1',
      courseId: '1',
      title: 'Tổng Quan Thị Trường BĐS Việt Nam',
      description: 'Nắm bắt bức tranh toàn cảnh thị trường bất động sản Việt Nam hiện nay',
      order: 1,
      createdAt: new Date(),
    },
    {
      id: 'm2',
      courseId: '1',
      title: 'Các Loại Hình Bất Động Sản',
      description: 'Phân biệt và hiểu rõ từng loại hình bất động sản trên thị trường',
      order: 2,
      createdAt: new Date(),
    },
    {
      id: 'm3',
      courseId: '1',
      title: 'Thuật Ngữ Chuyên Ngành',
      description: 'Nắm vững các thuật ngữ chuyên ngành bất động sản thường gặp',
      order: 3,
      createdAt: new Date(),
    },
  ],
  '2': [
    {
      id: 'm4',
      courseId: '2',
      title: 'Khai Thác Nhu Cầu Khách Hàng',
      description: 'Kỹ thuật đặt câu hỏi và lắng nghe để hiểu đúng nhu cầu khách hàng',
      order: 1,
      createdAt: new Date(),
    },
    {
      id: 'm5',
      courseId: '2',
      title: 'Tư Vấn Sản Phẩm Phù Hợp',
      description: 'Cách lựa chọn và giới thiệu sản phẩm BĐS phù hợp với từng khách hàng',
      order: 2,
      createdAt: new Date(),
    },
  ],
  '3': [
    {
      id: 'm6',
      courseId: '3',
      title: 'Xử Lý Phản Đối Từ Khách Hàng',
      description: 'Các kỹ thuật xử lý từ chối và phản đối phổ biến trong giao dịch BĐS',
      order: 1,
      createdAt: new Date(),
    },
    {
      id: 'm7',
      courseId: '3',
      title: 'Đàm Phán Giá & Chốt Giao Dịch',
      description: 'Nghệ thuật đàm phán giá và chốt sale thành công',
      order: 2,
      createdAt: new Date(),
    },
  ],
  '4': [
    {
      id: 'm8',
      courseId: '4',
      title: 'Quy Trình Pháp Lý Mua Bán',
      description: 'Hiểu rõ các bước pháp lý trong giao dịch mua bán bất động sản',
      order: 1,
      createdAt: new Date(),
    },
    {
      id: 'm9',
      courseId: '4',
      title: 'Hợp Đồng & Công Chứng',
      description: 'Quy trình soạn thảo hợp đồng và thủ tục công chứng BĐS',
      order: 2,
      createdAt: new Date(),
    },
  ],
  '5': [
    {
      id: 'm10',
      courseId: '5',
      title: 'Tư Vấn Căn Hộ The Emerald 68',
      description: 'Luyện tập tư vấn bán căn hộ cao cấp tại dự án The Emerald 68, Bình Dương',
      order: 1,
      createdAt: new Date(),
    },
  ],
  '6': [
    {
      id: 'm11',
      courseId: '6',
      title: 'Tư Vấn Nhà Phố Verosa Park',
      description: 'Luyện tập tư vấn bán nhà phố liền kề tại dự án Verosa Park, Quận 9',
      order: 1,
      createdAt: new Date(),
    },
  ],
  '7': [
    {
      id: 'm12',
      courseId: '7',
      title: 'Tư Vấn Biệt Thự Vinhomes Central Park',
      description: 'Luyện tập tư vấn bán biệt thự cao cấp tại dự án Vinhomes Central Park, Bình Thạnh',
      order: 1,
      createdAt: new Date(),
    },
  ],
  '8': [
    {
      id: 'm13',
      courseId: '8',
      title: 'Tư Vấn Đất Nền Long Thành',
      description: 'Luyện tập tư vấn bán đất nền khu vực Long Thành, gần sân bay quốc tế',
      order: 1,
      createdAt: new Date(),
    },
  ],
  '9': [
    {
      id: 'm14',
      courseId: '9',
      title: 'Tư Vấn Shophouse Vinhomes Grand Park',
      description: 'Luyện tập tư vấn bán shophouse thương mại tại Vinhomes Grand Park, TP. Thủ Đức',
      order: 1,
      createdAt: new Date(),
    },
  ],
};

export const mockLessons: Record<string, Lesson[]> = {
  'm1': [
    {
      id: 'l1',
      moduleId: 'm1',
      title: 'Bức Tranh Toàn Cảnh Thị Trường BĐS Việt Nam',
      content: '<h2>Tổng Quan Thị Trường Bất Động Sản Việt Nam</h2><p>Thị trường bất động sản Việt Nam là một trong những lĩnh vực kinh tế trọng điểm, đóng góp khoảng <strong>11-12% GDP</strong> cả nước. Với tốc độ đô thị hóa nhanh chóng và nhu cầu nhà ở ngày càng tăng, đây là ngành có tiềm năng phát triển mạnh mẽ.</p><h3>Các Phân Khúc Chính</h3><ul><li><strong>Phân khúc bình dân:</strong> Dưới 25 triệu/m² - phục vụ đa số người dân</li><li><strong>Phân khúc trung cấp:</strong> 25-50 triệu/m² - đối tượng trung lưu</li><li><strong>Phân khúc cao cấp:</strong> 50-80 triệu/m² - khách hàng có thu nhập cao</li><li><strong>Phân khúc hạng sang:</strong> Trên 80 triệu/m² - thượng lưu, nhà đầu tư</li></ul><h3>Các Khu Vực Trọng Điểm</h3><p>Thị trường BĐS tập trung chủ yếu tại:</p><ol><li><strong>TP. Hồ Chí Minh:</strong> Trung tâm kinh tế lớn nhất, giá BĐS cao nhất cả nước. Các quận trung tâm như Quận 1, Quận 3, Bình Thạnh có giá từ 80-200 triệu/m².</li><li><strong>Hà Nội:</strong> Thủ đô với nhu cầu nhà ở lớn. Khu vực Cầu Giấy, Nam Từ Liêm, Thanh Xuân đang phát triển mạnh.</li><li><strong>Bình Dương:</strong> Vệ tinh của TP.HCM, thu hút nhiều dự án căn hộ giá hợp lý từ 1.5-4 tỷ VNĐ.</li><li><strong>Đồng Nai:</strong> Hưởng lợi từ sân bay Long Thành, đất nền tăng giá mạnh.</li><li><strong>Đà Nẵng:</strong> Thị trường BĐS nghỉ dưỡng sôi động.</li></ol><h3>Xu Hướng Nổi Bật</h3><ul><li>Chuyển dịch ra vùng ven với hạ tầng giao thông phát triển</li><li>Nhu cầu căn hộ chung cư tăng mạnh tại các đô thị lớn</li><li>Phát triển BĐS xanh, thông minh, tiết kiệm năng lượng</li><li>Tích hợp công nghệ PropTech trong giao dịch</li></ul>',
      videoUrl: '',
      order: 1,
      createdAt: new Date(),
      resources: [
        { title: 'Báo cáo thị trường BĐS Q1/2024', url: '#' },
        { title: 'Bản đồ phân khúc giá BĐS Việt Nam', url: '#' },
      ],
    },
    {
      id: 'l2',
      moduleId: 'm1',
      title: 'Yếu Tố Ảnh Hưởng Đến Giá BĐS',
      content: '<h2>Các Yếu Tố Tác Động Đến Giá Bất Động Sản</h2><p>Hiểu rõ các yếu tố ảnh hưởng đến giá BĐS sẽ giúp bạn tư vấn chính xác hơn cho khách hàng.</p><h3>1. Vị Trí (Location)</h3><p>Đây là yếu tố quan trọng nhất quyết định giá trị BĐS:</p><ul><li>Khoảng cách đến trung tâm thành phố</li><li>Gần trường học, bệnh viện, siêu thị</li><li>Tiếp giáp đường lớn, gần ga metro</li><li>Khu vực an ninh, không ngập nước</li></ul><h3>2. Hạ Tầng Giao Thông</h3><p>Các dự án hạ tầng lớn tác động trực tiếp đến giá BĐS:</p><ul><li><strong>Metro Bến Thành - Suối Tiên:</strong> Tăng giá BĐS dọc tuyến 20-40%</li><li><strong>Sân bay Long Thành:</strong> Đất nền khu vực tăng 30-50% trong 3 năm</li><li><strong>Vành đai 3 TP.HCM:</strong> Kết nối vùng ven, giá BĐS tăng đáng kể</li></ul><h3>3. Pháp Lý</h3><ul><li>Sổ đỏ/sổ hồng riêng: Giá cao hơn 15-25% so với chưa có sổ</li><li>Quy hoạch: Đất nằm trong quy hoạch sẽ bị hạn chế giao dịch</li><li>Mục đích sử dụng đất: Đất ở, đất thương mại, đất nông nghiệp có giá khác nhau</li></ul><h3>4. Cung - Cầu Thị Trường</h3><p>Khi nguồn cung hạn chế mà nhu cầu cao, giá BĐS sẽ tăng và ngược lại. Người môi giới cần theo dõi sát diễn biến thị trường.</p>',
      videoUrl: '',
      order: 2,
      createdAt: new Date(),
      resources: [
        { title: 'Bảng giá đất TP.HCM 2024', url: '#' },
      ],
    },
  ],
  'm2': [
    {
      id: 'l3',
      moduleId: 'm2',
      title: 'Phân Loại Các Loại Hình Bất Động Sản',
      content: '<h2>Các Loại Hình Bất Động Sản Phổ Biến Tại Việt Nam</h2><p>Là một nhân viên tư vấn BĐS chuyên nghiệp, bạn cần nắm rõ đặc điểm, ưu nhược điểm của từng loại hình sản phẩm.</p><h3>1. Căn Hộ Chung Cư</h3><ul><li><strong>Đặc điểm:</strong> Sở hữu lâu dài hoặc có thời hạn (50 năm), diện tích 40-150m²</li><li><strong>Giá:</strong> Từ 1.5 tỷ - 15 tỷ VNĐ tùy vị trí và phân khúc</li><li><strong>Ưu điểm:</strong> An ninh tốt, tiện ích đầy đủ, phù hợp gia đình trẻ</li><li><strong>Khách hàng mục tiêu:</strong> Vợ chồng trẻ, người mua lần đầu, nhà đầu tư cho thuê</li></ul><h3>2. Nhà Phố</h3><ul><li><strong>Đặc điểm:</strong> Nhà liền kề trong dự án hoặc nhà phố riêng lẻ, 1 trệt 2-3 lầu</li><li><strong>Giá:</strong> Từ 5 tỷ - 25 tỷ VNĐ</li><li><strong>Ưu điểm:</strong> Sở hữu vĩnh viễn, có thể kinh doanh, không gian riêng tư</li><li><strong>Khách hàng mục tiêu:</strong> Gia đình truyền thống, người kinh doanh nhỏ</li></ul><h3>3. Biệt Thự</h3><ul><li><strong>Đặc điểm:</strong> Diện tích lớn từ 200-1000m², sân vườn riêng</li><li><strong>Giá:</strong> Từ 15 tỷ - 100+ tỷ VNĐ</li><li><strong>Ưu điểm:</strong> Không gian sống đẳng cấp, riêng tư tuyệt đối</li><li><strong>Khách hàng mục tiêu:</strong> Doanh nhân, người có thu nhập rất cao</li></ul><h3>4. Đất Nền</h3><ul><li><strong>Đặc điểm:</strong> Đất thổ cư hoặc đất dự án đã phân lô</li><li><strong>Giá:</strong> Từ 10 triệu - 200+ triệu/m² tùy khu vực</li><li><strong>Ưu điểm:</strong> Linh hoạt xây dựng, tiềm năng tăng giá cao</li><li><strong>Khách hàng mục tiêu:</strong> Nhà đầu tư dài hạn, người muốn tự xây nhà</li></ul><h3>5. Shophouse</h3><ul><li><strong>Đặc điểm:</strong> Nhà phố thương mại, vừa ở vừa kinh doanh</li><li><strong>Giá:</strong> Từ 8 tỷ - 30+ tỷ VNĐ</li><li><strong>Ưu điểm:</strong> Sinh lời kép (ở + kinh doanh), vị trí mặt tiền</li><li><strong>Khách hàng mục tiêu:</strong> Người kinh doanh, nhà đầu tư</li></ul>',
      videoUrl: '',
      order: 1,
      createdAt: new Date(),
      resources: [
        { title: 'So sánh các loại hình BĐS', url: '#' },
        { title: 'Bảng phân tích ROI theo loại hình', url: '#' },
      ],
    },
  ],
  'm3': [
    {
      id: 'l4',
      moduleId: 'm3',
      title: 'Thuật Ngữ BĐS Thường Gặp',
      content: '<h2>Từ Điển Thuật Ngữ Bất Động Sản</h2><p>Nắm vững các thuật ngữ chuyên ngành giúp bạn giao tiếp chuyên nghiệp hơn với khách hàng và đồng nghiệp.</p><h3>Thuật Ngữ Về Pháp Lý</h3><ul><li><strong>Sổ đỏ (GCNQSDĐ):</strong> Giấy chứng nhận quyền sử dụng đất</li><li><strong>Sổ hồng:</strong> Giấy chứng nhận quyền sở hữu nhà ở và quyền sử dụng đất</li><li><strong>Thổ cư:</strong> Đất ở, được phép xây dựng nhà ở</li><li><strong>Đất SKC:</strong> Đất sản xuất kinh doanh</li><li><strong>Quy hoạch 1/500:</strong> Bản đồ quy hoạch chi tiết dự án</li></ul><h3>Thuật Ngữ Về Giao Dịch</h3><ul><li><strong>Đặt cọc:</strong> Khoản tiền trả trước để giữ chỗ, thường 50-200 triệu VNĐ</li><li><strong>Booking:</strong> Phí giữ chỗ, thường 50-100 triệu VNĐ (có hoàn lại hoặc không)</li><li><strong>HĐMB:</strong> Hợp đồng mua bán</li><li><strong>Tiến độ thanh toán:</strong> Lịch trả tiền theo giai đoạn xây dựng</li><li><strong>Bàn giao thô:</strong> Bàn giao nhà chưa hoàn thiện nội thất</li><li><strong>Bàn giao full nội thất:</strong> Bàn giao nhà đã trang bị đầy đủ nội thất</li></ul><h3>Thuật Ngữ Về Tài Chính</h3><ul><li><strong>LTV (Loan to Value):</strong> Tỷ lệ cho vay trên giá trị tài sản, thường 70-80%</li><li><strong>Lãi suất ưu đãi:</strong> Lãi suất thấp trong 1-3 năm đầu, thường 6-8%/năm</li><li><strong>Lãi suất thả nổi:</strong> Lãi suất theo thị trường sau thời gian ưu đãi</li><li><strong>Ân hạn gốc:</strong> Thời gian chỉ trả lãi, chưa trả gốc</li><li><strong>ROI:</strong> Tỷ suất lợi nhuận trên vốn đầu tư</li></ul>',
      videoUrl: '',
      order: 1,
      createdAt: new Date(),
      resources: [
        { title: 'Từ điển thuật ngữ BĐS đầy đủ (PDF)', url: '#' },
      ],
    },
    {
      id: 'l4b',
      moduleId: 'm3',
      title: 'Cách Sử Dụng Thuật Ngữ Trong Tư Vấn',
      content: '<h2>Ứng Dụng Thuật Ngữ Khi Tư Vấn Khách Hàng</h2><p>Biết thuật ngữ là chưa đủ, bạn cần biết cách sử dụng chúng đúng ngữ cảnh để tạo sự tin tưởng với khách hàng.</p><h3>Nguyên Tắc Giao Tiếp</h3><ul><li><strong>Đơn giản hóa:</strong> Giải thích thuật ngữ bằng ngôn ngữ dễ hiểu cho khách hàng</li><li><strong>Ví dụ cụ thể:</strong> "Sổ đỏ nghĩa là anh/chị hoàn toàn sở hữu mảnh đất này và có thể mua bán, chuyển nhượng tự do"</li><li><strong>Không lạm dụng:</strong> Dùng vừa đủ để thể hiện chuyên môn, tránh gây khó hiểu</li></ul><h3>Ví Dụ Thực Tế</h3><p><strong>Tình huống:</strong> Khách hàng hỏi về tiến độ thanh toán</p><p><em>"Dạ, dự án này có tiến độ thanh toán rất linh hoạt ạ. Anh/chị chỉ cần đóng 30% trong năm đầu, phần còn lại trả dần theo tiến độ xây dựng. Ngoài ra, ngân hàng Vietcombank hỗ trợ vay lên đến 70% giá trị căn hộ với lãi suất ưu đãi 7%/năm trong 2 năm đầu."</em></p>',
      videoUrl: '',
      order: 2,
      createdAt: new Date(),
    },
  ],
  'm4': [
    {
      id: 'l5',
      moduleId: 'm4',
      title: 'Nghệ Thuật Khai Thác Nhu Cầu Khách Hàng',
      content: '<h2>Kỹ Thuật Khai Thác Nhu Cầu Khách Hàng BĐS</h2><p>Hiểu đúng nhu cầu khách hàng là bước quan trọng nhất trong quy trình bán hàng. Một người môi giới giỏi dành 70% thời gian để lắng nghe và chỉ 30% để nói.</p><h3>Phương Pháp SPIN Selling Trong BĐS</h3><ul><li><strong>Situation (Tình huống):</strong> "Hiện tại anh/chị đang ở đâu ạ? Gia đình mình có bao nhiêu thành viên?"</li><li><strong>Problem (Vấn đề):</strong> "Anh/chị có gặp khó khăn gì về chỗ ở hiện tại không ạ?"</li><li><strong>Implication (Hệ quả):</strong> "Nếu không có không gian riêng cho con học, liệu có ảnh hưởng đến việc học không ạ?"</li><li><strong>Need-payoff (Giải pháp):</strong> "Nếu có một căn hộ 3 phòng ngủ gần trường học thì sẽ giải quyết được vấn đề này đúng không ạ?"</li></ul><h3>Các Câu Hỏi Mở Hiệu Quả</h3><ol><li>"Anh/chị đang tìm kiếm BĐS với mục đích gì ạ? Để ở hay đầu tư?"</li><li>"Ngân sách anh/chị dự kiến trong khoảng bao nhiêu ạ?"</li><li>"Khu vực nào anh/chị ưu tiên? Có cần gần trường học hay bệnh viện không?"</li><li>"Về diện tích, anh/chị cần khoảng bao nhiêu m² là phù hợp?"</li><li>"Anh/chị có yêu cầu gì đặc biệt về hướng nhà, tầng hay view không ạ?"</li></ol><h3>Phân Loại Khách Hàng</h3><ul><li><strong>Khách mua ở:</strong> Ưu tiên tiện ích, an ninh, gần trường học/bệnh viện</li><li><strong>Khách đầu tư:</strong> Quan tâm lợi nhuận cho thuê, tiềm năng tăng giá</li><li><strong>Khách đầu cơ:</strong> Tìm kiếm mức giá thấp, dự án mới mở bán</li></ul>',
      videoUrl: '',
      order: 1,
      createdAt: new Date(),
      resources: [
        { title: 'Bộ câu hỏi khai thác nhu cầu khách hàng', url: '#' },
        { title: 'Mẫu phiếu khảo sát khách hàng BĐS', url: '#' },
      ],
    },
  ],
  'm5': [
    {
      id: 'l6',
      moduleId: 'm5',
      title: 'Kỹ Năng Tư Vấn Sản Phẩm BĐS',
      content: '<h2>Tư Vấn Sản Phẩm Phù Hợp Cho Khách Hàng</h2><p>Sau khi đã khai thác được nhu cầu, bước tiếp theo là tư vấn sản phẩm phù hợp nhất cho khách hàng.</p><h3>Công Thức FAB (Features - Advantages - Benefits)</h3><ul><li><strong>Features (Đặc điểm):</strong> "Căn hộ này có diện tích 75m², 2 phòng ngủ, 2 WC"</li><li><strong>Advantages (Ưu điểm):</strong> "Thiết kế thông minh, tận dụng tối đa không gian sống"</li><li><strong>Benefits (Lợi ích):</strong> "Với 2 phòng ngủ riêng biệt, vợ chồng anh/chị vẫn có không gian riêng cho con học bài mà không bị ảnh hưởng"</li></ul><h3>Kỹ Thuật So Sánh</h3><p>Luôn chuẩn bị 2-3 sản phẩm để khách hàng so sánh:</p><table><tr><th>Tiêu chí</th><th>Căn A (2.1 tỷ)</th><th>Căn B (2.5 tỷ)</th><th>Căn C (3.2 tỷ)</th></tr><tr><td>Diện tích</td><td>55m²</td><td>70m²</td><td>85m²</td></tr><tr><td>Phòng ngủ</td><td>1PN + 1</td><td>2PN</td><td>3PN</td></tr><tr><td>Tầng</td><td>Tầng 8</td><td>Tầng 15</td><td>Tầng 22</td></tr><tr><td>View</td><td>Nội khu</td><td>Sông</td><td>Thành phố</td></tr></table><h3>Lưu Ý Quan Trọng</h3><ul><li>Luôn đặt lợi ích khách hàng lên trên hoa hồng</li><li>Trung thực về ưu và nhược điểm sản phẩm</li><li>Tạo urgency tự nhiên: "Hiện tại dự án còn rất ít căn tầng đẹp ạ"</li></ul>',
      videoUrl: '',
      order: 1,
      createdAt: new Date(),
      resources: [
        { title: 'Bảng so sánh mẫu sản phẩm BĐS', url: '#' },
      ],
    },
  ],
  'm6': [
    {
      id: 'l7',
      moduleId: 'm6',
      title: 'Xử Lý 10 Phản Đối Phổ Biến Nhất',
      content: '<h2>Xử Lý Phản Đối Từ Khách Hàng Trong Bán BĐS</h2><p>Phản đối là phần tự nhiên của quá trình bán hàng. Khách hàng phản đối vì họ đang quan tâm nhưng chưa đủ tin tưởng. Dưới đây là 10 phản đối phổ biến nhất và cách xử lý.</p><h3>1. "Giá cao quá!"</h3><p><strong>Cách xử lý:</strong> "Em hiểu anh/chị cảm thấy giá cao. Nhưng nếu so sánh với các dự án cùng phân khúc trong khu vực như [Dự án A] đang bán 45 triệu/m², thì dự án mình với mức 38 triệu/m² là rất cạnh tranh. Hơn nữa, với vị trí và tiện ích 5 sao, giá trị này sẽ tăng 15-20% khi dự án hoàn thiện."</p><h3>2. "Để tôi suy nghĩ thêm"</h3><p><strong>Cách xử lý:</strong> "Dạ, em hoàn toàn tôn trọng quyết định của anh/chị. Tuy nhiên, hiện tại chủ đầu tư đang có chương trình ưu đãi chiết khấu 5% chỉ áp dụng đến cuối tuần này. Anh/chị có điều gì còn băn khoăn để em giải đáp thêm không ạ?"</p><h3>3. "Tôi muốn xem thêm dự án khác"</h3><p><strong>Cách xử lý:</strong> "Dạ đúng rồi ạ, mua nhà là quyết định lớn nên anh/chị nên tìm hiểu kỹ. Em có thể giúp anh/chị so sánh với một số dự án khác để thấy được ưu điểm vượt trội của dự án mình."</p><h3>4. "Khu vực này xa trung tâm quá"</h3><p><strong>Cách xử lý:</strong> "Em hiểu lo ngại của anh/chị. Tuy nhiên, với tuyến Metro số 1 sẽ hoạt động vào năm 2025, khoảng cách di chuyển về trung tâm chỉ còn 20 phút. Và chính vì vậy, giá BĐS khu vực này đang thấp hơn 40% so với trung tâm - đây là cơ hội đầu tư rất tốt."</p><h3>5. "Tôi chưa đủ tiền"</h3><p><strong>Cách xử lý:</strong> "Dạ, anh/chị không cần thanh toán 100% ngay ạ. Chủ đầu tư hỗ trợ tiến độ thanh toán chỉ 30% đến khi nhận nhà. Ngoài ra, ngân hàng đối tác hỗ trợ vay lên đến 70% với lãi suất chỉ 6.5%/năm trong 2 năm đầu."</p>',
      videoUrl: '',
      order: 1,
      createdAt: new Date(),
      resources: [
        { title: 'Kịch bản xử lý phản đối (PDF)', url: '#' },
        { title: 'Video: Xử lý phản đối nâng cao', url: '#' },
      ],
    },
  ],
  'm7': [
    {
      id: 'l8',
      moduleId: 'm7',
      title: 'Nghệ Thuật Đàm Phán Giá & Chốt Sale',
      content: '<h2>Kỹ Năng Đàm Phán Giá và Chốt Giao Dịch BĐS</h2><p>Chốt sale là bước quyết định thành công của toàn bộ quá trình bán hàng. Một người môi giới giỏi biết khi nào nên chốt và chốt bằng cách nào.</p><h3>Các Dấu Hiệu Khách Hàng Sẵn Sàng Mua</h3><ul><li>Hỏi chi tiết về tiến độ thanh toán, lãi suất ngân hàng</li><li>Hỏi về thời gian bàn giao, chính sách bảo hành</li><li>Đưa người thân đi xem lại lần 2</li><li>Hỏi về thủ tục đặt cọc, hồ sơ cần chuẩn bị</li><li>So sánh giữa các căn trong cùng dự án</li></ul><h3>5 Kỹ Thuật Chốt Sale Hiệu Quả</h3><ol><li><strong>Chốt giả định:</strong> "Vậy anh/chị chọn căn góc hay căn giữa ạ?" (giả định khách đã quyết định mua)</li><li><strong>Chốt khan hiếm:</strong> "Hiện tại tầng 18 chỉ còn 2 căn cuối cùng, nếu anh/chị quan tâm thì mình nên giữ chỗ sớm ạ"</li><li><strong>Chốt ưu đãi:</strong> "Chương trình chiết khấu 8% chỉ áp dụng cho 50 khách đầu tiên trong tuần này"</li><li><strong>Chốt tổng kết:</strong> Tóm tắt tất cả lợi ích rồi hỏi "Với những ưu điểm này, anh/chị thấy sao ạ?"</li><li><strong>Chốt cảm xúc:</strong> "Anh/chị tưởng tượng mỗi sáng thức dậy nhìn ra view sông Sài Gòn, con cái được chơi ở công viên nội khu an toàn..."</li></ol><h3>Đàm Phán Giá</h3><ul><li>Không bao giờ giảm giá ngay, hãy tạo giá trị trước</li><li>Đàm phán trên tổng giá trị gói (nội thất, phí quản lý) thay vì giá gốc</li><li>Đề xuất giải pháp win-win: "Em không thể giảm giá thêm, nhưng em sẽ xin chủ đầu tư tặng thêm gói nội thất 200 triệu"</li></ul>',
      videoUrl: '',
      order: 1,
      createdAt: new Date(),
      resources: [
        { title: 'Bộ kịch bản chốt sale BĐS', url: '#' },
      ],
    },
  ],
  'm8': [
    {
      id: 'l9',
      moduleId: 'm8',
      title: 'Quy Trình Pháp Lý Mua Bán BĐS Tại Việt Nam',
      content: '<h2>Quy Trình Pháp Lý Giao Dịch Bất Động Sản</h2><p>Nắm vững quy trình pháp lý là yêu cầu bắt buộc để bảo vệ quyền lợi cho cả người mua và người bán.</p><h3>Bước 1: Kiểm Tra Pháp Lý Bất Động Sản</h3><ul><li>Xác minh giấy chứng nhận quyền sử dụng đất (sổ đỏ/sổ hồng)</li><li>Kiểm tra quy hoạch tại UBND quận/huyện</li><li>Xác minh tình trạng thế chấp tại ngân hàng</li><li>Kiểm tra tranh chấp, khiếu nại liên quan</li><li>Xác nhận mục đích sử dụng đất phù hợp</li></ul><h3>Bước 2: Đặt Cọc</h3><ul><li>Ký hợp đồng đặt cọc (thường 10% giá trị BĐS)</li><li>Quy định rõ thời hạn, điều kiện hoàn cọc/phạt cọc</li><li>Có công chứng hoặc chứng thực hợp đồng đặt cọc</li></ul><h3>Bước 3: Ký Hợp Đồng Mua Bán</h3><ul><li>Soạn hợp đồng mua bán theo mẫu quy định</li><li>Công chứng tại văn phòng công chứng</li><li>Cả hai bên ký trước mặt công chứng viên</li><li>Nộp thuế chuyển nhượng (2% giá trị hợp đồng)</li></ul><h3>Bước 4: Sang Tên Sổ</h3><ul><li>Nộp hồ sơ tại Văn phòng đăng ký đất đai</li><li>Thời gian xử lý: 10-30 ngày làm việc</li><li>Lệ phí trước bạ: 0.5% giá trị BĐS</li></ul><h3>Thuế & Phí Liên Quan</h3><ul><li><strong>Thuế thu nhập cá nhân:</strong> 2% giá trị chuyển nhượng (người bán chịu)</li><li><strong>Lệ phí trước bạ:</strong> 0.5% giá trị BĐS (người mua chịu)</li><li><strong>Phí công chứng:</strong> Theo biểu phí quy định, thường 0.1-0.5% giá trị</li><li><strong>Phí thẩm định:</strong> 0.15% giá trị (tối đa 5 triệu VNĐ)</li></ul>',
      videoUrl: '',
      order: 1,
      createdAt: new Date(),
      resources: [
        { title: 'Checklist kiểm tra pháp lý BĐS', url: '#' },
        { title: 'Luật Đất đai 2024 - Tóm tắt điểm mới', url: '#' },
      ],
    },
  ],
  'm9': [
    {
      id: 'l10',
      moduleId: 'm9',
      title: 'Hợp Đồng Mua Bán & Thủ Tục Công Chứng',
      content: '<h2>Hợp Đồng Mua Bán Bất Động Sản & Công Chứng</h2><p>Hợp đồng mua bán là văn bản pháp lý quan trọng nhất trong giao dịch BĐS. Người môi giới cần hiểu rõ để tư vấn chính xác cho khách hàng.</p><h3>Nội Dung Bắt Buộc Trong HĐMB</h3><ol><li><strong>Thông tin các bên:</strong> Họ tên, CMND/CCCD, địa chỉ người mua và người bán</li><li><strong>Thông tin BĐS:</strong> Địa chỉ, diện tích, số sổ, mục đích sử dụng</li><li><strong>Giá bán:</strong> Bằng số và bằng chữ, đồng tiền thanh toán (VNĐ)</li><li><strong>Phương thức thanh toán:</strong> Chuyển khoản, tiền mặt, tiến độ thanh toán</li><li><strong>Thời hạn bàn giao:</strong> Ngày cụ thể bàn giao BĐS</li><li><strong>Quyền và nghĩa vụ:</strong> Của cả người mua và người bán</li><li><strong>Điều khoản phạt:</strong> Vi phạm hợp đồng, chậm thanh toán</li><li><strong>Cam kết:</strong> BĐS không tranh chấp, không thế chấp</li></ol><h3>Quy Trình Công Chứng</h3><ol><li>Chuẩn bị hồ sơ: Sổ đỏ/hồng bản gốc, CCCD, hộ khẩu, giấy kết hôn (nếu có)</li><li>Đến văn phòng công chứng cùng hai bên</li><li>Công chứng viên kiểm tra hồ sơ và xác minh</li><li>Đọc và ký hợp đồng trước sự chứng kiến của công chứng viên</li><li>Thanh toán phí công chứng và nhận bản hợp đồng có đóng dấu</li></ol><h3>Lưu Ý Cho Người Môi Giới</h3><ul><li>Luôn khuyên khách hàng đọc kỹ hợp đồng trước khi ký</li><li>Không ký hợp đồng tay (không công chứng) cho giao dịch lớn</li><li>Kiểm tra kỹ thông tin BĐS trên sổ trước khi giao dịch</li><li>Lưu giữ bản sao hợp đồng cho hồ sơ cá nhân</li></ul>',
      videoUrl: '',
      order: 1,
      createdAt: new Date(),
      resources: [
        { title: 'Mẫu HĐMB nhà đất chuẩn pháp lý', url: '#' },
        { title: 'Danh sách văn phòng công chứng TP.HCM', url: '#' },
      ],
    },
  ],
  'm10': [
    {
      id: 'l11',
      moduleId: 'm10',
      title: 'Tư Vấn Bán Căn Hộ The Emerald 68',
      content: '<h2>Nhiệm Vụ: Tư Vấn Bán Căn Hộ The Emerald 68</h2><p><strong>Sản phẩm:</strong> Căn hộ The Emerald 68</p><ul><li><strong>Giá:</strong> 2.5 - 4.5 tỷ VNĐ</li><li><strong>Diện tích:</strong> 55 - 98m²</li><li><strong>Loại căn:</strong> 2 - 3 phòng ngủ</li><li><strong>Vị trí:</strong> Đại lộ Bình Dương, TP. Thuận An, Bình Dương</li></ul><h3>Tiện Ích Nổi Bật</h3><ul><li>Hồ bơi tràn bờ tầng thượng, view panorama</li><li>Phòng gym & yoga hiện đại theo chuẩn 5 sao</li><li>Công viên nội khu rộng 2 hecta với cây xanh bao phủ</li><li>Khu vui chơi trẻ em, đường chạy bộ, sân tennis</li><li>Trung tâm thương mại, siêu thị ngay tầng trệt</li><li>An ninh 24/7 với hệ thống camera giám sát</li></ul><h3>Lợi Thế Vị Trí</h3><ul><li>Ngay trung tâm TP. Thuận An, Bình Dương</li><li>Cách TP.HCM chỉ 20 phút di chuyển qua Quốc lộ 13</li><li>Gần Aeon Mall Bình Dương, Lotte Mart</li><li>Liền kề khu công nghiệp VSIP - nhu cầu cho thuê rất cao</li><li>Hạ tầng giao thông phát triển mạnh mẽ</li></ul><h3>Chính Sách Bán Hàng</h3><ul><li>Thanh toán 30% đến khi nhận nhà</li><li>Ngân hàng hỗ trợ vay 70%, lãi suất 6.5%/năm (2 năm đầu)</li><li>Chiết khấu 3% khi thanh toán nhanh</li><li>Tặng gói nội thất 150 triệu cho 100 khách đầu tiên</li></ul><h3>Nhiệm Vụ Của Bạn</h3><p><strong>Hãy tư vấn và thuyết phục khách hàng AI mua căn hộ này.</strong> Sử dụng giọng nói tự nhiên như đang trong cuộc gọi tư vấn thực tế. Hãy khai thác nhu cầu, giới thiệu sản phẩm và xử lý phản đối từ khách hàng!</p>',
      videoUrl: '',
      order: 1,
      createdAt: new Date(),
      resources: [
        { title: 'Bảng giá The Emerald 68 cập nhật', url: '#' },
        { title: 'Brochure dự án The Emerald 68', url: '#' },
        { title: 'Mặt bằng căn hộ chi tiết', url: '#' },
      ],
    },
  ],
  'm11': [
    {
      id: 'l12',
      moduleId: 'm11',
      title: 'Tư Vấn Bán Nhà Phố Verosa Park',
      content: '<h2>Nhiệm Vụ: Tư Vấn Bán Nhà Phố Verosa Park</h2><p><strong>Sản phẩm:</strong> Nhà phố Verosa Park</p><ul><li><strong>Giá:</strong> 10.5 - 18 tỷ VNĐ</li><li><strong>Diện tích đất:</strong> 75 - 120m²</li><li><strong>Kết cấu:</strong> 1 trệt 3 lầu</li><li><strong>Vị trí:</strong> Đường Liên Phường, TP. Thủ Đức (Quận 9 cũ), TP.HCM</li></ul><h3>Đặc Điểm Nổi Bật</h3><ul><li>Thiết kế 1 trệt 3 lầu, 4-5 phòng ngủ rộng rãi</li><li>Sân vườn riêng trước nhà, không gian xanh mát</li><li>Gara ô tô riêng, đỗ được 2 xe</li><li>An ninh 24/7 với hệ thống bảo vệ chuyên nghiệp</li><li>Cổng ra vào nhận diện khuôn mặt và thẻ từ</li><li>Khu compound khép kín, an toàn cho trẻ em</li></ul><h3>Tiện Ích Khu Đô Thị</h3><ul><li>Clubhouse với hồ bơi, gym, spa</li><li>Công viên nội khu với đường dạo bộ</li><li>Khu BBQ và sân chơi cộng đồng</li><li>Gần trường quốc tế TH School, British International School</li><li>Gần Vincom Mega Mall, bệnh viện quận Thủ Đức</li></ul><h3>Chính Sách Bán Hàng</h3><ul><li>Thanh toán linh hoạt 35% trong 12 tháng</li><li>Ngân hàng Techcombank hỗ trợ vay 65%, lãi suất 7%/năm (18 tháng đầu)</li><li>Chiết khấu 5% khi thanh toán sớm 95%</li><li>Sổ hồng riêng, sở hữu vĩnh viễn</li></ul><h3>Nhiệm Vụ Của Bạn</h3><p><strong>Hãy tư vấn và thuyết phục khách hàng AI mua nhà phố Verosa Park.</strong> Khách hàng là gia đình có con nhỏ đang tìm nhà rộng rãi, an ninh tốt. Hãy nhấn mạnh vào không gian sống và tiện ích cho gia đình!</p>',
      videoUrl: '',
      order: 1,
      createdAt: new Date(),
      resources: [
        { title: 'Bảng giá Verosa Park cập nhật', url: '#' },
        { title: 'Brochure dự án Verosa Park', url: '#' },
      ],
    },
  ],
  'm12': [
    {
      id: 'l13',
      moduleId: 'm12',
      title: 'Tư Vấn Bán Biệt Thự Vinhomes Central Park',
      content: '<h2>Nhiệm Vụ: Tư Vấn Bán Biệt Thự Vinhomes Central Park</h2><p><strong>Sản phẩm:</strong> Biệt thự Vinhomes Central Park</p><ul><li><strong>Giá:</strong> 35 - 80 tỷ VNĐ</li><li><strong>Diện tích:</strong> 300 - 500m²</li><li><strong>Loại hình:</strong> Biệt thự đơn lập và biệt thự song lập</li><li><strong>Vị trí:</strong> Khu đô thị Vinhomes Central Park, 208 Nguyễn Hữu Cảnh, Quận Bình Thạnh, TP.HCM</li></ul><h3>Đặc Điểm Nổi Bật</h3><ul><li>Diện tích đất 300-500m², xây dựng 2-3 tầng</li><li>Sân vườn riêng rộng rãi với cây xanh cảnh quan</li><li>Bể bơi riêng trong khuôn viên biệt thự</li><li>4-6 phòng ngủ, phòng khách rộng, phòng làm việc riêng</li><li>Gara đỗ 2-3 ô tô, hệ thống smart home</li><li>Quản lý bởi Vinhomes - thương hiệu uy tín hàng đầu</li></ul><h3>Tiện Ích Đẳng Cấp</h3><ul><li>Công viên ven sông Sài Gòn rộng 14 hecta</li><li>Landmark 81 - tòa nhà cao nhất Việt Nam ngay bên cạnh</li><li>Trường quốc tế Vinschool, bệnh viện Vinmec</li><li>Trung tâm thương mại Vincom Center, rạp CGV</li><li>Hồ bơi, gym, spa, sân tennis chuẩn quốc tế</li><li>An ninh đa lớp: bảo vệ, camera AI, cổng nhận diện</li></ul><h3>Chính Sách Bán Hàng</h3><ul><li>Thanh toán 30% ký HĐMB, phần còn lại theo tiến độ</li><li>Ngân hàng BIDV, Vietcombank hỗ trợ vay 70%</li><li>Lãi suất ưu đãi 6%/năm trong 24 tháng đầu</li><li>Sổ hồng riêng, sở hữu vĩnh viễn</li></ul><h3>Nhiệm Vụ Của Bạn</h3><p><strong>Hãy tư vấn và thuyết phục khách hàng AI mua biệt thự Vinhomes Central Park.</strong> Khách hàng là doanh nhân thành đạt đang tìm kiếm không gian sống đẳng cấp xứng tầm. Hãy nhấn mạnh vào giá trị thương hiệu Vinhomes, view sông Sài Gòn và đẳng cấp sống!</p>',
      videoUrl: '',
      order: 1,
      createdAt: new Date(),
      resources: [
        { title: 'Bảng giá biệt thự Vinhomes Central Park', url: '#' },
        { title: 'Brochure khu biệt thự', url: '#' },
        { title: 'Video 3D tour biệt thự mẫu', url: '#' },
      ],
    },
  ],
  'm13': [
    {
      id: 'l14',
      moduleId: 'm13',
      title: 'Tư Vấn Bán Đất Nền Long Thành',
      content: '<h2>Nhiệm Vụ: Tư Vấn Bán Đất Nền Long Thành</h2><p><strong>Sản phẩm:</strong> Đất nền Long Thành</p><ul><li><strong>Giá:</strong> 15 - 25 triệu/m²</li><li><strong>Diện tích:</strong> 80 - 200m² (đã phân lô)</li><li><strong>Pháp lý:</strong> Sổ đỏ riêng từng nền</li><li><strong>Vị trí:</strong> Huyện Long Thành, tỉnh Đồng Nai</li></ul><h3>Đặc Điểm Nổi Bật</h3><ul><li>Sổ đỏ riêng từng nền, pháp lý minh bạch</li><li>Hạ tầng hoàn thiện: đường nhựa 12-16m, điện, nước, cống thoát</li><li>Đã có giấy phép xây dựng, xây nhà ngay</li><li>Mặt tiền đường lớn, dân cư hiện hữu</li><li>Cách sân bay quốc tế Long Thành chỉ 5-10km</li></ul><h3>Tiềm Năng Tăng Giá</h3><ul><li><strong>Sân bay Long Thành:</strong> Dự kiến hoạt động 2026, công suất 25 triệu hành khách/năm giai đoạn 1</li><li><strong>Cao tốc Bến Lức - Long Thành:</strong> Kết nối trực tiếp miền Tây với sân bay</li><li><strong>Đường Vành đai 3:</strong> Đi qua Long Thành, nâng cao kết nối vùng</li><li><strong>Khu công nghiệp:</strong> VSIP 3, Amata mở rộng, thu hút lao động lớn</li><li>Giá đất khu vực đã tăng trung bình 15-25%/năm trong 5 năm qua</li></ul><h3>Chính Sách Bán Hàng</h3><ul><li>Đặt cọc 100 triệu VNĐ giữ chỗ</li><li>Thanh toán 50% ký công chứng, 50% còn lại trong 6 tháng</li><li>Hỗ trợ vay ngân hàng lên đến 50% giá trị</li><li>Chiết khấu 3% thanh toán nhanh 100%</li><li>Miễn phí sang tên sổ đỏ cho khách mua trong tháng</li></ul><h3>Nhiệm Vụ Của Bạn</h3><p><strong>Hãy tư vấn và thuyết phục khách hàng AI mua đất nền Long Thành.</strong> Khách hàng là nhà đầu tư đang tìm kiếm cơ hội đầu tư đất nền gần sân bay Long Thành. Hãy phân tích tiềm năng tăng giá và pháp lý rõ ràng!</p>',
      videoUrl: '',
      order: 1,
      createdAt: new Date(),
      resources: [
        { title: 'Bản đồ vị trí và quy hoạch Long Thành', url: '#' },
        { title: 'Phân tích tiềm năng đầu tư đất nền', url: '#' },
      ],
    },
  ],
  'm14': [
    {
      id: 'l15',
      moduleId: 'm14',
      title: 'Tư Vấn Bán Shophouse Vinhomes Grand Park',
      content: '<h2>Nhiệm Vụ: Tư Vấn Bán Shophouse Vinhomes Grand Park</h2><p><strong>Sản phẩm:</strong> Shophouse Vinhomes Grand Park</p><ul><li><strong>Giá:</strong> 12 - 25 tỷ VNĐ</li><li><strong>Diện tích:</strong> 80 - 150m² (diện tích sàn xây dựng 200-400m²)</li><li><strong>Kết cấu:</strong> 1 trệt 3 lầu, vừa ở vừa kinh doanh</li><li><strong>Vị trí:</strong> Khu đô thị Vinhomes Grand Park, TP. Thủ Đức, TP.HCM</li></ul><h3>Đặc Điểm Nổi Bật</h3><ul><li>Vừa ở vừa kinh doanh - sinh lời kép</li><li>Mặt tiền đường lớn 20-30m, visibility tuyệt vời</li><li>Khu dân cư đông đúc với hơn 50,000 cư dân Vinhomes Grand Park</li><li>Thiết kế linh hoạt: tầng trệt kinh doanh, tầng trên ở hoặc cho thuê</li><li>Phù hợp mở: nhà hàng, café, showroom, phòng khám, văn phòng</li></ul><h3>Lợi Thế Kinh Doanh</h3><ul><li><strong>Lượng khách hàng sẵn có:</strong> 50,000+ cư dân trong khu đô thị</li><li><strong>Vị trí mặt tiền:</strong> Thu hút khách qua lại từ trục đường chính</li><li><strong>Thương hiệu Vinhomes:</strong> Gia tăng giá trị thương mại và uy tín</li><li><strong>Doanh thu cho thuê ước tính:</strong> 40-80 triệu/tháng (tầng trệt)</li><li><strong>ROI cho thuê:</strong> Khoảng 5-8%/năm</li></ul><h3>Tiện Ích Xung Quanh</h3><ul><li>Vincom Mega Mall ngay trong khu đô thị</li><li>Trường Vinschool các cấp</li><li>Công viên 36 hecta - lớn nhất Đông Nam Á</li><li>Hồ bơi, gym, khu thể thao đa năng</li><li>Gần tuyến Metro số 1, Xa lộ Hà Nội</li></ul><h3>Chính Sách Bán Hàng</h3><ul><li>Thanh toán 20% ký HĐMB</li><li>Ngân hàng hỗ trợ vay 70%, lãi suất 7.5%/năm (12 tháng đầu)</li><li>Chiết khấu 6% thanh toán sớm</li><li>Tặng gói hoàn thiện mặt tiền kinh doanh trị giá 300 triệu</li><li>Sổ hồng riêng, sở hữu lâu dài</li></ul><h3>Nhiệm Vụ Của Bạn</h3><p><strong>Hãy tư vấn và thuyết phục khách hàng AI mua shophouse Vinhomes Grand Park.</strong> Khách hàng là chủ doanh nghiệp nhỏ đang tìm mặt bằng kinh doanh kết hợp nhà ở. Hãy nhấn mạnh vào tiềm năng kinh doanh và lượng cư dân sẵn có!</p>',
      videoUrl: '',
      order: 1,
      createdAt: new Date(),
      resources: [
        { title: 'Bảng giá shophouse Vinhomes Grand Park', url: '#' },
        { title: 'Phân tích doanh thu kinh doanh shophouse', url: '#' },
        { title: 'Mặt bằng shophouse chi tiết', url: '#' },
      ],
    },
  ],
};

export const mockUserProgress: UserProgress[] = [
  {
    id: 'up1',
    userId: '1',
    courseId: '1',
    enrollmentDate: new Date('2024-02-15'),
    progressPercentage: 45,
    status: 'in_progress',
    lastAccessed: new Date('2024-02-24'),
  },
  {
    id: 'up2',
    userId: '1',
    courseId: '2',
    enrollmentDate: new Date('2024-02-20'),
    progressPercentage: 10,
    status: 'in_progress',
    lastAccessed: new Date('2024-02-23'),
  },
];
